// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOpfNrKvvLEK9ZjSuKg2Y9C0Ok5n7bsU',
    appId: '1:434623142543:web:7806be6ed63750bb2baefa',
    messagingSenderId: '434623142543',
    projectId: 'conviva-63d6a',
    authDomain: 'conviva-63d6a.firebaseapp.com',
    storageBucket: 'conviva-63d6a.firebasestorage.app',
    measurementId: 'G-P21QJBZWP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpnrM3HqzmVfrvGf3BubKLJbIN1ZBHi80',
    appId: '1:434623142543:android:f2f97f240496fde92baefa',
    messagingSenderId: '434623142543',
    projectId: 'conviva-63d6a',
    storageBucket: 'conviva-63d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUYEUCqNFMi3UMWlln3e7qUKOGBFLybM',
    appId: '1:434623142543:ios:988dd3533cdbf0d42baefa',
    messagingSenderId: '434623142543',
    projectId: 'conviva-63d6a',
    storageBucket: 'conviva-63d6a.firebasestorage.app',
    iosBundleId: 'com.example.conviva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUYEUCqNFMi3UMWlln3e7qUKOGBFLybM',
    appId: '1:434623142543:ios:988dd3533cdbf0d42baefa',
    messagingSenderId: '434623142543',
    projectId: 'conviva-63d6a',
    storageBucket: 'conviva-63d6a.firebasestorage.app',
    iosBundleId: 'com.example.conviva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHOpfNrKvvLEK9ZjSuKg2Y9C0Ok5n7bsU',
    appId: '1:434623142543:web:7c8f5827606f10a52baefa',
    messagingSenderId: '434623142543',
    projectId: 'conviva-63d6a',
    authDomain: 'conviva-63d6a.firebaseapp.com',
    storageBucket: 'conviva-63d6a.firebasestorage.app',
    measurementId: 'G-D25HL8S832',
  );
}
